### ISSUE TITLE
AMD support?

### ISSUE THREAD

**Issue by petersondrew** [immense/knockout-pickadate#2]
Have you considered adding AMD support?

**Comment by cmbankester** [comment]
I haven't looked into AMD very thoroughly yet. As of right now, therefore, I don't anticipate adding AMD support. That may change in the future.

**Comment by petersondrew** [comment]
No worries, thanks for the response. It was trivial enough on my end to wrap the function definition in an AMD compatible way.

Drew Peterson

-----Original Message-----

**Comment by cmbankester** [comment]
Cool deal. I'm going to close this issue. We can open a new one if AMD support ever gets added to the proposed feature set.
