### ISSUE TITLE
Year

### ISSUE THREAD

**Issue by jmbalanag** [immense/knockout-pickadate#3]
I really like this tool, but is there way for the year to be clickable/editable?

**Comment by cmbankester** [comment]
You should be able to enable year/month editing via the pickadate_options binding:

``` html
<input type="text" data-bind="pickadate: some_variable, pickadate_options: {selectYears: true, selectMonths: true}">
```

[Have a look here](http://amsul.ca/pickadate.js/date/#options) for all the options that are supported by pickadate. You should be able to pass any of them into the pickadate_options binding
